### ISSUE TITLE
Roadmap to Beta release

### ISSUE THREAD

**Issue by nikfp** [nikfp/Buildthings#1]
This is meant to be a roadmap to a beta release. Items will be added and tracked as needed. 

To Do: 
- [x] Work on loading states
- [x] Add Project detail page
- [x] Add Projects list
- [x] Add project edit form to details page
- [x] Add contacts model
- [x] Add contacts resolvers
- [x] Integrate contacts manager
- [ ] Add sort function utilities
- [ ] Build generic search bar
- [ ] Integrate contacts picker
- [ ] Add scope model
- [ ] Add scope resolvers
- [ ] Add scopes functionality to project detail
- [ ] Add ability to add items to scope
- [ ] Add scope tracking details
- [ ] Start scheduling view
- [ ] Add roles to users
- [ ] Add user manager for admins
- [ ] Add permissions layer
- [ ] Add PDF output for schedules
- [ ] Integrate file storage using presigned URLS
- [ ] integrate file upload to presigned URLS
- [ ] Implement file details connected to scopes
